- hosts: all
  vars:
    warName: sample.war
    warRemotePath: /home/tomcat

  tasks:
  package:
    name:
      "tomcat9"
      state: present
    name: Download WAR to server
      copy:
        src: sample.war
        dest: /var/lib/tomcat9/webapps/
   
